- location/gql_queries.py
- location/models.py
- location/schema.py
- setup.py
Add get_queryset to models, migrate userDistricts to UserDistrict model
> FHIR fine grained security

- location/apps.py
part of TICKET https://openimis.atlassian.net/browse/OE0-4
Fixed some wrong perms for 'Location' module according to https://openimis.atlassian.net/wiki/spaces/OP/pages/1775173658/openIMIS+Authorities
> OE0-4: added missing perms and fixed perms value in location module

- location/models.py
- location/test_graphql.py
- location/test_helpers.py
Since this is especially visible in the graphql, I took the opportunity to add the corresponding tests.
> OMT-280 Cannot query a just created Region

- location/apps.py
- location/services.py
Changes:
- Added HF level CodeSystem to the module configuration
- Added a service to retrieve HF level CodeSystem
[https://openimis.atlassian.net/browse/OE0-77](https://openimis.atlassian.net/browse/OE0-77)
> OE0-77: Add OrganizationPHLegalForm and OrganizationPHActivity + update OrganizationHFLegalForm Code Systems

- location/gql_mutations.py
Change required for [Contained Resources in FHR API](https://github.com/openimis/openimis-be-api_fhir_r4_py/pull/69)
> OAI-61: Return HF in create_or_update function

- location/gql_mutations.py
- location/services.py
[https://openimis.atlassian.net/browse/OPL-90](https://openimis.atlassian.net/browse/OPL-90)
Changes:
- Moved create_or_update code of Location and HealthFacility models to class services, allowing easy reuse and signal binding (i.e. for subscriptions)
> OPL-90: Extend the notifications to allow subscribing Health Facilities

- location/test_helpers.py
part of TICKET: https://openimis.atlassian.net/browse/OTC-607
> OTC-607: added 'create health facility'  helpers for batch-run tests

- location/services.py
TICKET: [OP-808](https://openimis.atlassian.net/browse/OP-808)
> OP-808: District creator automatically assigned to it

- location/gql_mutations.py
TICKET: [OP-811](https://openimis.atlassian.net/browse/OP-811)
> OP-811: Remove user district on location delete

- location/migrations/0007_auto_20211103_1046.py
> Django 3.1

- location/schema.py
Required by [OP-854](https://github.com/openimis/openimis-be-location_py/pull/new/feature/OP-854)
> OP-854: Added filtering HF Str by list of district uuids

- location/models.py
Ticket: https://openimis.atlassian.net/browse/OP-976
Changes:
- Districts now properly filtered.
> OP-976: Location type filter fixed for superuser.

- location/models.py
This is used among other places when downloading locations
> Location parents/children were not working on PG

- location/gql_mutations.py
https://openimis.atlassian.net/browse/OP-1057
> OP-1057: Deleting of a location with it's children doesn't delete all the children 

- location/services.py
https://openimis.atlassian.net/browse/OP-948
> OP-948: modular IMIS strange behaviour of the Location register

- location/gql_mutations.py
- location/schema.py
- location/services.py
Ticket: https://openimis.atlassian.net/browse/OP-946
FE PR: https://github.com/openimis/openimis-fe-location_js/pull/32
Changes:
- Added BE check for validating location code.
- Added graphql query for checking uniqueness of location code
[OP-946]: https://openimis.atlassian.net/browse/OP-946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OP-946: Check and graphql query - unique location code.

- location/gql_mutations.py
- location/schema.py
- location/services.py
Ticket: https://openimis.atlassian.net/browse/OP-986
BE part of the ticket.
Changes:
- Added graphql query for checking if the HF code is unique
- BE now blocks adding new HF with existing code, or editing existing HF to a taken code
> OP-986: HFs unique code checks.

- location/models.py
- location/schema.py
- location/test_graphql.py
https://openimis.atlassian.net/browse/OP-1047
> OP-1047: modular IMIS: objects not belonging to the territorial range of a user displayed and even can be manipulated

- .github/workflows/openmis-module-test.yml
- location/schema.py
Ticket:
https://openimis.atlassian.net/browse/OTC-876
Changes:
- Added permission check for location code and health facility code validations.
> OTC-876: Permissions check added.

- .github/workflows/openmis-module-test.yml
- location/migrations/0009_add_location_read_right.py
- location/models.py
- location/schema.py
TICKET: [OTC-797](https://openimis.atlassian.net/browse/OTC-797)
Requires [ClaimAdmin location property](https://github.com/openimis/openimis-be-claim_py/pull/72) to work. 
Requires [Core isClaimAdmin](https://github.com/openimis/openimis-be-core_py/pull/147) to work.
[OTC-797]: https://openimis.atlassian.net/browse/OTC-797?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> OTC-797: Fix teritorial range for CA and EO

- location/schema.py
Ticket: https://openimis.atlassian.net/browse/OTC-874
Changes:
- Query added enrolment officers locations.
> OTC-874: Query for enrolment officers locations.

- location/gql_mutations.py
- location/services.py
Ticket:
https://openimis.atlassian.net/browse/OTC-951
Changes:
- moved duplication code check from 'async' to 'update_or_create' service
- added check for incoming code and already existing one
> OTC-951: allowed editing location without changing code

- location/gql_queries.py
- location/schema.py
https://openimis.atlassian.net/browse/OTC-878
> OTC-878: add all the qgl mutations and queries

- location/gql_queries.py
https://openimis.atlassian.net/browse/OTC-986
This PR changes permission in resolve location in HealthFacilityGQLType to location instead of hf perms.
> OTC-986: change perms in hf location

- location/models.py
Ticket:
https://openimis.atlassian.net/browse/OTC-970
Changes:
- extended validation check with validity_to filtering outside of the validate function for user's districts
> OTC-970: extended validity_to filtering

- location/gql_queries.py
https://openimis.atlassian.net/browse/OTC-973
It is an update of: https://github.com/openimis/openimis-be-location_py/pull/63
> OTC-973: use is_authenticated on some gql queries

- location/gql_queries.py
- location/schema.py
https://openimis.atlassian.net/browse/OTC-817
> OTC-973: switch location check to is_authorized

- location/gql_queries.py
- location/schema.py
Spotted while working on: https://openimis.atlassian.net/browse/OTC-1008
I added a row security if statement.
> OTC-1008: update resolve health facility str to use row security

- location/schema.py
Ticket:
https://openimis.atlassian.net/browse/OTC-1016
Changes:
- replaced "location permission check" with "is_authenticated check"
> OTC-1016: deleted check for location perms from Health Facility str resolver

- location/gql_queries.py
Ticket:
https://openimis.atlassian.net/browse/OTC-1027
Changes:
- changed locationGQLType to allow filtering with parents on every level
> OTC-1027: changed locationGQLType to allow filtering with parents on every level

- location/gql_queries.py
https://openimis.atlassian.net/browse/OP-1419
This PR changes perm check in resolve_client_mutation_id to is_authorized.
> OP-1419: change perm check when fetching locations

- location/services.py
https://openimis.atlassian.net/browse/OP-1446
This PR doesn't allow to update historical health facilities.
> OP-1446: don't let to update historical hf

- location/gql_queries.py
https://openimis.atlassian.net/browse/OTC-1097
Added phone in Health Facilities filter list
> OTC-1097: Searching for HFs using phone number causing an error

- location/models.py
Ticket:
https://openimis.atlassian.net/browse/OTC-1075
Changes:
- admin has all user districts returned
Related:
https://github.com/openimis/openimis-be-core_py/pull/178
> Feature/otc 1075: admin has all user districts returned

- location/services.py
[https://openimis.atlassian.net/browse/CM-190](https://openimis.atlassian.net/browse/CM-190)
> CM-190 Added generic location filter

- location/services.py
Ticket: https://openimis.atlassian.net/browse/ONI-105
Changes:
- Missing backend checks added for validity of the contract start/end dates.
> ONI-105: Backend checks added for contract dates.

- location/apps.py
https://openimis.atlassian.net/browse/OP-1518
This PR changes the way how config is loaded.
> OP-1518: load config

- locale/en/LC_MESSAGES/django.po
- location/services.py
https://openimis.atlassian.net/browse/OP-1544
This PR add locale directory to the module.
> OP-1544: update translations in location module

- location/apps.py
- location/services.py
Ticket: https://openimis.atlassian.net/browse/ONI-105
Changes:
- Added check for contract dates on setting
> ONI-105-2: Added check for contract dates as mandatory on setting.

- location/models.py
This is blocking deployments of the main branch
> OP-1555 is_imis_admin not available in main (core)

- location/models.py
Reverts openimis/openimis-be-location_py#107
> Revert "MERGING RELEASE branches"

- location/services.py
- location/test_graphql.py
https://openimis.atlassian.net/browse/OP-1661
Modifying HF was crashing due to the HealthFacility.status check
> OP-1661: Issue Executing Step number  8 - Test Case: Modify HF 

- location/models.py
https://openimis.atlassian.net/browse/OP-1774
> OP-1774: User with non-admin or non-superuser throws an exception while fetching locations
